% Example call
% template_export_sv( 'subsystem1_tb/fec_top','240229','systemverilog','','clk')

function template_export_sv(block_name,target_hdl_directory,myfavouritelanguage,moduleprefix,clock_name,reset_name)
% 
% hdlset_param('rx_deframer_wrapper_tb', 'SubsystemReuse', 'Atomic and Virtual');
% set_param('rx_deframer_wrapper_tb','DefaultParameterBehavior','inlined'); % codegen parameter needed for reuse of references.  

% Get the current date as a string
dateStr = datestr(now, 'yyyymmdd');

% Create the full directory name
dirName = ['x_deframer_' dateStr];

% Check if the directory already exists
if exist(dirName, 'dir')
    % If it does, increment the directory name
    i = 1;
    while exist([dirName '.' num2str(i)], 'dir')
        i = i + 1;
    end
    dirName = [dirName '.' num2str(i)];
end

if isempty(target_hdl_directory)
target_hdl_directory = dirName;
end

block_name_for_sv_export = get_param(block_name,'Name');

disp(block_name)
% hdlset_param(block_name,'BalanceDelays','on'); % safest thing AND make sure to check the "Delay Balancing" report
%hdlset_param(gcs, 'DownToArrayIndexing', 'on');
% hdlset_param(block_name, 'DistributedPipelining', 'off');
% hdlrestoreparams(block_name); %  resetting all parameters to default values. (This is a safe option)

% Set SubSystem HDL parameters for descrambler to make it a blackbox
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'Architecture', 'BlackBox');
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'AddClockEnablePort', 'off');
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'EntityName', 'scrb_top');
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'ImplementationLatency', 0);
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'InlineConfigurations', 'off');
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'ResetInputPort', 'rstn');
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'VHDLArchitectureName', '');
% hdlset_param('rx_deframer_wrapper_tb/rx_deframer_wrapper/rx_deframer/descrambler/scrb_top', 'VHDLComponentLibrary', '');

makehdl(block_name, ...
    'targetlanguage',myfavouritelanguage,...              % https://uk.mathworks.com/help/hdlcoder/ug/target.html#buiuh3k-20
    'Traceability','on',...                           % https://uk.mathworks.com/help/hdlcoder/ug/code-generation-report-parameters.html#buiuh3k-40
    'PreserveDesignDelays','on',...                   % https://uk.mathworks.com/help/hdlcoder/ug/pipelining-parameters.html#bu_om9f-1
    'ResourceReport','on',...                         % https://uk.mathworks.com/help/hdlcoder/ug/code-generation-report-parameters.html#buiuh3k-42
    'DeleteUnusedPorts','off',...                     % https://uk.mathworks.com/help/hdlcoder/ug/general-optimization-parameters.html#mw_f7b18e22-cd9f-459b-9db9-7a076aa75a2d
    'OptimizationReport','on',...                     % https://uk.mathworks.com/help/hdlcoder/ug/code-generation-report-parameters.html#buiuh3k-44
    'ResetType','Asynchronous',...                    % https://uk.mathworks.com/help/hdlcoder/ug/reset-and-clock-enable-settings.html#buiuh3k-60
    'ResetAssertedLevel','active-low',...             % https://uk.mathworks.com/help/hdlcoder/ug/reset-and-clock-enable-settings.html#buiuh3k-62
    'ClockInputPort',clock_name,...         % https://uk.mathworks.com/help/hdlcoder/ug/clock-and-timing-controller-settings.html#buiuh3k-64
    'ClockInputs','Single',...                        % https://uk.mathworks.com/help/hdlcoder/ug/clock-and-timing-controller-settings.html#buiuh3k-78
    'ClockEnableInputPort','clk_enable',...           % https://uk.mathworks.com/help/hdlcoder/ug/clock-enable-settings.html#buiuh3k-68
    'MinimizeClockEnables','on',...                   % https://uk.mathworks.com/help/hdlcoder/ug/minimize-clock-enables-and-reset-signals.html
    'ResetInputPort',reset_name,...                     % https://uk.mathworks.com/help/hdlcoder/ug/reset-and-clock-enable-settings.html#buiuh3k-73
    'UserComment','(c) Intel',...                     % https://uk.mathworks.com/help/hdlcoder/ug/comment-in-header.html
    'BlockGenerateLabel','_gen',...                   % https://uk.mathworks.com/help/hdlcoder/ug/generate-statements-labels.html#mw_53c144bf-ca0b-4336-a223-4726c5b26dfb
    'InstanceGenerateLabel','_gen',...                % https://uk.mathworks.com/help/hdlcoder/ug/generate-statements-labels.html#mw_54959ae3-fe60-42c4-bae8-5e6f76f24f44
    'InstancePostfix','_duplicate',...                % https://uk.mathworks.com/help/hdlcoder/ug/generate-statements-labels.html#mw_9d7a2ae6-6c81-46a4-8e68-ec763336396b
    'InstancePrefix','u_',...                         % https://uk.mathworks.com/help/hdlcoder/ug/generate-statements-labels.html#mw_943198bc-ed5a-4cc6-884b-398c7756d1a8
    'ModulePrefix',moduleprefix,...                   % https://uk.mathworks.com/help/hdlcoder/ref/makehdl.html (search for moduleprefix)
    'SubsystemReuse', 'Atomic and Virtual',...
    'VectorPrefix','vec_',...                         % https://uk.mathworks.com/help/hdlcoder/ug/generate-statements-labels.html#mw_d78e159b-8559-4ab2-ac4a-714fa92dfdad
    'UseAggregatesForConst','off',...                 % https://uk.mathworks.com/help/hdlcoder/ug/rtl-customizations-for-constants-and-matlab-function-blocks.html#buiuh3k-192
    'InitializeBlockRAM','on',...                     % https://uk.mathworks.com/help/hdlcoder/ug/rtl-customizations-for-rams.html#buiuh3k-217
    'RAMArchitecture','WithClockEnable',...           % https://uk.mathworks.com/help/hdlcoder/ug/rtl-customizations-for-rams.html#buiuh3k-219
    'NoResetInitializationMode','None',...            % https://uk.mathworks.com/help/hdlcoder/ug/no-reset-registers-initialization.html
    'MinimizeIntermediateSignals','off',...           % https://uk.mathworks.com/help/hdlcoder/ug/rtl-style.html#buiuh3k-209
    'MaskParameterAsGeneric','on',...                 % https://uk.mathworks.com/help/hdlcoder/ug/rtl-style.html#buiuh3k-215
    'SafeZeroConcat','on',...                         % https://uk.mathworks.com/help/hdlcoder/ug/rtl-annotations.html#buiuh3k-203
    'CustomFileHeaderComment','',...                  % https://uk.mathworks.com/help/hdlcoder/ug/file-comment-customization.html#mw_17fc13e9-9712-4bb2-a001-7597e41e7a1f
    'DateComment','on',...                            % https://uk.mathworks.com/help/hdlcoder/ug/rtl-annotations.html
    'RequirementComments','on',...                    % https://uk.mathworks.com/help/hdlcoder/ug/file-comment-customization.html#buiuh3k-211
    'GenerateValidationModel','off',...                % https://uk.mathworks.com/help/hdlcoder/ug/model-generation-for-hdl-code.html#buiuh3k-35
    'LayoutStyle','AutoArrange',...                   % https://uk.mathworks.com/help/hdlcoder/ug/naming-options.html#mw_78d763a5-1a29-46a4-8d3c-910004fd81eb
    'AutoRoute','on',...                              % https://uk.mathworks.com/help/hdlcoder/ug/naming-options.html#mw_8a49f8bf-5fe2-4314-86c2-e02fdeeb1d4c
    'HighlightFeedbackLoops','on',...                 % https://uk.mathworks.com/help/hdlcoder/ug/diagnostics-for-optimizations.html#buiuh3k-256
    'CodeGenerationOutput','GenerateHDLCode',...      % https://uk.mathworks.com/help/hdlcoder/ug/code-generation-output.html
    'GenerateHDLCode','on',...                        % https://uk.mathworks.com/help/hdlcoder/ug/code-generation-output.html
    'TargetDirectory',target_hdl_directory...         % https://uk.mathworks.com/help/hdlcoder/ug/target.html#buiuh3k-25
    )

    % 'GeneratedModel','on',...                         % https://uk.mathworks.com/help/hdlcoder/ug/model-generation-for-hdl-code.html#mw_6f50add8-8eeb-4127-978f-40520c38a643
    % 'HDLCodingStandard','Industry',...                % https://uk.mathworks.com/help/hdlcoder/ug/choose-coding-standard-and-report-options.html


% makehdltb(block_name_for_sv_export, ...
%     'TargetLanguage','systemverilog', ...
%     'TargetDirectory',target_hdl_directory, ...
%     'ResetAssertedLevel','active-low' ...
%     )



% 
% makehdltb(block_name_for_sv_export, ...
%     'TargetLanguage','systemverilog', ...
%     'Traceability','on',...                           
%     'PreserveDesignDelays','on',...                   
%     'ResourceReport','on',...                         
%     'DeleteUnusedPorts','off',...                     
%     'OptimizationReport','on',...                     
%     'ResetType','Asynchronous',...                    
%     'ResetAssertedLevel','active-low',...             
%     'ClockInputPort','clk',...                        
%     'ClockInputs','Single',...                        
%     'ClockEnableInputPort','clk_enable',...           
%     'MinimizeClockEnables','on',...                   
%     'ResetInputPort','rstn',...                       
%     'UserComment','(c) Intel',...                     
%     'BlockGenerateLabel','_gen',...                   
%     'InstanceGenerateLabel','_gen',...                
%     'InstancePostfix','',...                          
%     'InstancePrefix','u_',...                         
%     'VectorPrefix','vec_',...                         
%     'UseAggregatesForConst','off',...                 
%     'InitializeBlockRAM','on',...                     
%     'RAMArchitecture','WithClockEnable',...           
%     'NoResetInitializationMode','None',...            
%     'MinimizeIntermediateSignals','off',...           
%     'MaskParameterAsGeneric','on',...                 
%     'SafeZeroConcat','on',...                         
%     'CustomFileHeaderComment','',...                  
%     'DateComment','on',...                            
%     'RequirementComments','on',...                    
%     'GenerateValidationModel','on',...                
%     'LayoutStyle','AutoArrange',...                   
%     'AutoRoute','on',...                              
%     'HighlightFeedbackLoops','on',...                 
%     'CodeGenerationOutput','GenerateHDLCode',...      
%     'GenerateHDLCode','on',...                        
%     'TargetDirectory',target_hdl_directory ...
%     )
